# Used globals : 
# nutrient_limiter

number:
  # nutrient daily limit
  - platform: template
    name: Nutrient upper daily limit
    id: nutrient_daily_limit_ml
    unit_of_measurement: 'ml'
    min_value: 0
    max_value: 1000
    step: 0.1
    optimistic: true
    restore_value: true
    initial_value: 180
    on_value:
      then:
        lambda: 'nutrient_limiter->setLimit(x);'

sensor:
  - platform: template
    name: "Nutrient daily flow"
    id: nutrient_daily_alert_bucket
    lambda: 'return nutrient_limiter->getTotalAddedOnPeriod();'
